openapistack/openapi-client-axios

DOCS.md
README.md
src/client.test.ts
src/client.ts
src/typegen/typegen.test.ts
src/typegen/typegen.ts
src/types/client.ts

This PR implements a new way to call operations, without using the `operationId`.
A new paths dictionary is added to the `OpenAPIClient` instance, where each entry contains the operation functions for each method.
Examples:
```
client.paths['/pets'].get(); // GET /pets
client.paths['/pets'].post(); // POST /pets
client.paths['/pets/{petId}'].put(1); // PUT /pets/1
client.paths['/pets/{petId}/owner/{ownerId}'].get({ petId: 1, ownerId: 2 }) ; // GET /pets/1/owner/2
```

Implement paths dictionary for operations

---

src/typegen/typegen.ts

A stopgap solution to #26.
operationId is turned into a string instead.
A more permanent solution would be to use the same type name converter that the dtsgenerator uses for operationId's in order to sanitize both the method names and type definitions.

simple fix to escape method names in typegen

---

package-lock.json
package.json
src/client.ts

`openapi-schema-validation` has been replaced
You can find the message here https://www.npmjs.com/package/openapi-schema-validation
Updated the code to use `openapi-schema-validator`.
Came across this problem while using `openapi-client-axios-typegen`. openapi-schema-validation has an unused `fs` import which breaks certain webpack builds.

replaced deprecated openapi-schema-validation

---

DOCS.md
src/client.test.ts
src/client.ts
src/typegen/typegen.test.ts
src/typegen/typegen.ts

Related: #30 
Hello!
💁‍♀️ This PR allows users to override the default strategy for mapping `operationId` to methods on the OpenAPI Client.
In an API I work on, we have an OpenAPI specification that uses `operationId` that follow a convention that captures controller and action (e.g. `produce.getVegetables`, `produce.getFruits`, etc.) We use `express-openapi-validator` to enforce our specification on an Express server.
In #30, we discussed an opportunity to allow method names to be derived from `operationId` through a user-configurable "name factory", which would decide how `operationId` is mapped to method names on the client. Here it is!
Given the following simple OpenAPI specification:
<details>
<summary>openapi.yaml</summary>
```yaml
openapi: 3.0.0
info:
title: User Configurable …
```

Operation method names are configurable via `transformOperationName`

---

package-lock.json
src/client.ts
src/types/json-schema-ref-parser.d.ts

* Bump `@apidevtools/json-schema-ref-parser` lock from **9.0.6** to **9.0.7**
* Describe `dereference` method and `$RefParserOptions` from `json-schema-ref-parser` library, for a future error preventing at type-check stage
* Fix incorrect `dereference` method usage, `options` argument are **not marked as optional** in orig documentation and should b always passed (with default values)

Fix initSync undocomented usage of dereference method [#55]

---

README.md
package-lock.json
package.json
src/client.test.ts
src/client.ts

**Why are you seeing this?**
We have an orthographic error on the client interface (_true story_).
```
import OpenAPIClientAxios from 'openapi-client-axios';
const api = new OpenAPIClientAxios({ definition: 'https://example.com/api/openapi.json' });
api.init();
// api.initalized  ===> api.initialized
```
**If merged then what?**
This slightly breaks the API, so I'm shipping a major (v4.0.0).

fix: orthographic error on the client init method (typo)

---

DOCS.md
README.md
src/client.test.ts
src/client.ts

We have an API construction where we need to add in the workspaceId (like a tenant identifier) in every request in the path:
`http://server/api/<workspaceId>/do-something`
This is currently handled by passing in the workspaceId as parameter in every request, but it would be great if we can just set defaultParameters when creating an OpenAPIClient.
```
const api = new OpenAPIClientAxios({
definition: 'http://localhost:5000/swagger/private/swagger.json',
defaultParameters: {
workspaceId: '63e90965-0797-4393-8f5d-d2e8fae0e8d0'
}
});
```

Ability to add defaultParameters

---

DOCS.md
src/index.ts

This patch introduces support to importing the function that uses `DTSGenerator` to create the typings for the client, in a programmatic way :]

feat: add programmatic support to type generation

---

src/typegen/typegen.test.ts
src/typegen/typegen.ts

Hello ! 
Thank you very much for this library 🙏 ! [At Pennylane](https://github.com/pennylane-hq), we use it a lot to improve the communication between our frontend & backend engineers. 🎉 
Since we updated the library's version, in the `client.d.ts` file, the responses's types have been prefixed with a " $ ". 
I guess that is because the "$" is now added by the dts-generator library ?
**How to reproduce** : 
Run `./typegen ../__tests__/resources/example-pet-api.openapi.yml` and have a look at the generated ts file. You will see that each response type is something like `OperationResponse<Paths.OperationId.Responses.$$200>` .
I was wondering if you will be ok to remove the extra "$".
  I didn’t see any contributing guides, so let me know if I’ve done something wrong.
  Thanks,

fix(type) : Remove extra $ in responses types

---

DOCS.md

Documentation says `transformOperationMethods` when it should have been `transformOperationMethod`.
Grrr!!!

fix bad example

---

packages/openapi-client-axios/package-lock.json
packages/openapi-client-axios/package.json
packages/typegen/package-lock.json
packages/typegen/package.json

There was an inconsistency between `openapi-axios-client` and `typegen`: one package-lock json was v1 while the other was 2.x. Now they are both v2.
Also, I updated everything that can be updated without breaking tests, compilation and linting.

chore(deps): bump deps and regenerate package-lock.json with NPM 8

---

packages/openapi-client-axios/package-lock.json
packages/openapi-client-axios/package.json
packages/openapi-client-axios/src/types/client.ts
packages/typegen/package-lock.json
packages/typegen/package.json

This is a breaking change to support Axios 0.25. The type signature in Axios has changed, the list version of `headers` isn't accepted any more.
I guess it's better to apply this after merging #103

Axios 0.25 support

---

packages/openapi-client-axios/src/client.test.ts
packages/openapi-client-axios/src/client.ts

Hey @anttiviljami, 
This PR fixes https://github.com/anttiviljami/openapi-client-axios/issues/111.
I wrote a test to reproduce the issue and it's passing with these changes.
I'm not sure if this is the right way to fix it, but let me know what you think.
Thanks,
Joao

Fix: single-element array params not being passed as array

---

packages/openapi-client-axios/package-lock.json
packages/openapi-client-axios/package.json
packages/typegen/package-lock.json

Update open api types to the latest version to fix typescript 4.8 compatibility issues, as per: https://github.com/kogosoftwarellc/open-api/pull/830

chore(deps): update openapi-types

---

packages/typegen/src/__tests__/resources/example-aws-api-gateway-rest.openapi.json
packages/typegen/src/typegen-aws-api-gateway-rest.test.ts
packages/typegen/src/typegen.ts

See: #150 
Changes for review to the typegen package:
- Created: `packages/typegen/src/__tests__/resources/example-aws-api-gateway-rest.openapi.json` as an example of the type of Open API spec generated by using the GetExport method on an AWS API Gateway REST API
- Created a matching test file: `packages/typegen/src/typegen-aws-api-gateway-rest.test.ts`
- Changes to `packages/typegen/src/typegen.ts` to ignore operations that have no operationId
Failing test case error before fix - one of two caused in two separate loops to `generateMethodForOperation`:
```sh
typegen for openapi spec with missing operation IDs › exports a Client
TypeError: Cannot read properties of undefined (reading 'replace')
13 | // rule from 'dts-generator' jsonSchema.ts
14 | function convertKeyToTypeName(key: string): …
```

Fix uncaught error for empty operation IDs

---

packages/openapi-client-axios/src/client.ts

Yesterday i came across with this typo while using openapi-client-axios.

Typo: Replace fesponse with response

---

packages/typegen/src/typegen.ts

Parameters can be defined for all verbs within a path at the path level in the OpenAPI spec. E.g.
```
paths:
/user/{userId}:
parameters:
....
get: # parameters apply here as well
```
However, the typegen code wouldn't find those because it was only searching for exported types under the operationId and didn't include searches that apply to the overall path. This change adds directives to check the path-level for applicable request parameters as well.

Search normalized paths for parameters as well

---

packages/typegen/package-lock.json
packages/typegen/src/typegen.test.ts
packages/typegen/src/typegen.ts

This PR omits the optional on parameters if path parameters are used. This can be enabled using the CLI options disableOptionalPathParameters.
The reason for this PR is that path parameters are always required and it doesn't make sense that they should be optional.

refactor(typegen): path parameters required in output

---

packages/typegen/src/typegen.ts

The option is forced to `true` from [this commit](https://github.com/openapistack/openapi-client-axios/commit/e9d85e5060bcab9a486584e1144abd076fea4b58), but the argument is not typed correctly, which make the parameter unusuable

fix(typegen): fix disableOptionalPathParameters

---

packages/typegen/src/typegen.test.ts
packages/typegen/src/typegen.ts

This PR allows for a banner to be added at the top of the generated file.
I required this for disabling eslint.

feat(typegen): banner comment option
